(ns hoplon.ui.app.content)

(def states
 (sorted-map
   :alabama              "Alabama"
   :alaska               "Alaska"
   :arizona              "Arizona"
   :arkansas             "Arkansas"
   :california           "California"
   :colorado             "Colorado"
   :connecticut          "Connecticut"
   :delaware             "Delaware"
   :district-of-columbia "District of Columbia"
   :florida              "Florida"
   :georgia              "Georgia"
   :hawaii               "Hawaii"
   :idaho                "Idaho"
   :illiois              "Illinois"
   :indiana              "Indiana"
   :iowa                 "Iowa"
   :kansas               "Kansas"
   :kentucky             "Kentucky"
   :louisiana            "Louisiana"
   :maine                "Maine"
   :montata              "Montana"
   :nebraska             "Nebraska"
   :nevada               "Nevada"
   :new-hampshire        "New Hampshire"
   :new-jersey           "New Jersey"
   :new-mexico           "New Mexico"
   :new-york             "New York"
   :north-calolina       "North Carolina"
   :north-dakota         "North Dakota"
   :ohio                 "Ohio"
   :oklahoma             "Oklahoma"
   :oregon               "Oregon"
   :maryland             "Maryland"
   :massachusetts        "Massachusetts"
   :michigan             "Michigan"
   :minnesota            "Minnesota"
   :mississippi          "Mississippi"
   :missouri             "Missouri"
   :pennyslvania         "Pennsylvania"
   :rhode-island         "Rhode Island"
   :south-carolina       "South Carolina"
   :south-dakota         "South Dakota"
   :tennessee            "Tennessee"
   :texas                "Texas"
   :utah                 "Utah"
   :vermont              "Vermont"
   :virginia             "Virginia"
   :washington           "Washington"
   :west-virginia        "West Virginia"
   :wisconsin            "Wisconsin"
   :wyoming              "Wyoming"))
